name: Repack Excel
on:
  workflow_dispatch:
  repository_dispatch:
    types: [Repack]

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: false

      - name: Setup ssh key
        run: |
          mkdir -p ~/.ssh

          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

          ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts

      - name: Clone repository
        run: |
          git clone --depth 1 git@github.com:beichen23333/BlueArchive-Translation.git tool
          git clone --depth 1 git@github.com:beichen23333/BA-Text-Translation.git BA-Text-Translation

          cp -r tool/* . && rm -rf tool

      - name: Set up Python 3.12
        uses: actions/setup-python@v6
        with:
          python-version: '3.12'

      - name: Install requirements
        run: |
          sudo apt-get install zip
          sudo apt-get install libsqlcipher-dev
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install sqlcipher3
          pip install pysqlcipher3

      - name: Get Version info
        id: v
        run: |
          bash other/version.sh JP info_jp.json >> "$GITHUB_OUTPUT"

      - name: Cache FlatData
        id: cache-flatdata
        uses: actions/cache@v4
        with:
          path: Extracted
          key: JP-flatdata-${{ steps.v.outputs.FLATDATA_VERSION_NAME }}

      - name: Cache Unpack
        id: cache-unpack
        uses: actions/cache@v4
        with:
          path: workspace/
          key: JP-unpack-${{ steps.v.outputs.BA_VERSION_NAME }}

      - name: Update table
        run: |
          chmod +x update/update_table.sh
          update/update_table.sh JP

      - name: Read DB Key
        id: dbkey
        run: |
          DB_KEY="$(cat BA-Text-Translation/Key.txt | tr -d '\r\n')"
          echo "DB_KEY=$DB_KEY" >> "$GITHUB_ENV"

      - name: Patch Catalog
        env:
          PYTHONUNBUFFERED: "1"
        run: |
          python repack_excel.py "BA-Text-Translation/日服备份.zip" Extracted/FlatData TableBundles workspace . --db_key "$DB_KEY"
          python -m patch_table_catalog

      - name: Prepare Release Assets
        id: prepare_assets
        run: |
          mkdir -p release_assets
          cp 日配/*.db release_assets/
          cp 日配/TableCatalog.bytes release_assets/

          echo "RELEASE_TAG=JP-${{ steps.v.outputs.BA_VERSION_NAME }}-$(date +%Y%m%d%H%M)" >> "$GITHUB_OUTPUT"

      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.prepare_assets.outputs.RELEASE_TAG }}
          name: "Repack Excel - ${{ steps.v.outputs.BA_VERSION_NAME }}"
          body: |
            ExcelDB.db打包。
            游戏版本: ${{ steps.v.outputs.BA_VERSION_NAME }}
            FL版本: ${{ steps.steps.v.outputs.FLATDATA_VERSION_NAME }}
          files: |
            release_assets/*.db
            release_assets/TableCatalog.bytes
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
